spring.application.name=demo
# Configuración del servidor
server.port=8082

spring.datasource.url=jdbc:h2:mem:dataBase
spring.datasource.driver-class-name=
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

# Configuración de recursos estáticos
spring.web.resources.cache.cachecontrol.max-age=3600

# Configuración de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false